name: Explore
version: 0.1.0.0
github: "logiczsniper/Explore-Hungeon"
license: BSD3
author: "Logan Czernel"
maintainer: "lczernel@gmail.com"
copyright: "2019 L. Czernel"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/logiczsniper/Explore#readme>

dependencies:
  - base >= 4.7 && < 5
  - gloss
  - proteaaudio

library:
  source-dirs: src

executables:
  Explore-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Explore

tests:
  Explore-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Explore
