module ImageConstants where

import GameTypes (ImageId)

borderBottom  :: ImageId
borderBottom                    = 1
borderTop  :: ImageId
borderTop                       = 2
borderRight :: ImageId
borderRight                     = 3
borderLeft :: ImageId
borderLeft                      = 4
borderTopLeft :: ImageId
borderTopLeft                   = 5
borderTopRight :: ImageId
borderTopRight                  = 6
borderBottomRight :: ImageId
borderBottomRight               = 7
borderBottomLeft :: ImageId
borderBottomLeft                = 9

floorDryBottom :: ImageId
floorDryBottom                  = 10
floorDryTop :: ImageId
floorDryTop                     = 11
floorDryRight :: ImageId
floorDryRight                   = 12
floorDryLeft :: ImageId
floorDryLeft                    = 13
floorDryTopLeft :: ImageId
floorDryTopLeft                 = 14
floorDryTopRight :: ImageId
floorDryTopRight                = 15
floorDryBottomRight :: ImageId
floorDryBottomRight             = 16
floorDryBottomLeft :: ImageId
floorDryBottomLeft              = 17
floorDryDoor :: ImageId
floorDryDoor                    = 18
floorDryPlain :: ImageId
floorDryPlain                   = 19
floorWetBottom :: ImageId
floorWetBottom                  = 20
floorWetTop :: ImageId
floorWetTop                     = 21
floorWetRight :: ImageId
floorWetRight                   = 22
floorWetLeft :: ImageId
floorWetLeft                    = 23
floorWetTopLeft :: ImageId
floorWetTopLeft                 = 24
floorWetTopRight :: ImageId
floorWetTopRight                = 25
floorWetBottomRight :: ImageId
floorWetBottomRight             = 26
floorWetBottomLeft :: ImageId
floorWetBottomLeft              = 27
floorWetPlain :: ImageId
floorWetPlain                   = 28
floorPlantsOne :: ImageId
floorPlantsOne                  = 29
floorPlantsTwo :: ImageId
floorPlantsTwo                  = 30
floorPlantsThree :: ImageId
floorPlantsThree                = 31

wallSecretClosed :: ImageId
wallSecretClosed                = 32
wallSecretCracked :: ImageId
wallSecretCracked               = 33
wallSecretOpen :: ImageId
wallSecretOpen                  = 34
wallStandardBoarded :: ImageId
wallStandardBoarded             = 35
wallStandardDoor :: ImageId
wallStandardDoor                = 36
wallStandardFancy :: ImageId
wallStandardFancy               = 37
wallStandardPlain :: ImageId
wallStandardPlain               = 38
wallPlantsOne :: ImageId
wallPlantsOne                   = 39
wallPlantsTwo :: ImageId
wallPlantsTwo                   = 40
wallPlantsThree :: ImageId
wallPlantsThree                 = 41